### ISSUE TITLE
Support for 1.16.5

### ISSUE THREAD

**Issue by TheMarksmanXII** [SnowShock35/jei-integration#10]
I know that most 1.16.4 Forge mods work with 1.16.5, but when I tried loading a bunch of client-side mods from 1.16.4 on 1.16.5, my world crashed while loading. So does this mod's 1.16.4 version work with 1.16.5 or do you need to make a new one? I'm going through each mod I used to find out if it has a 1.16.5 version.

**Comment by SnowShock35** [comment]
So the mod technically would work with 1.16.5, but iirc the mods.toml sets the specific version that it can be loaded with. I will update it to 1.16.5 when JEI has a build for 1.16.5 and I have a spare five minutes to do so.

Thanks for your patience. :-)

**Comment by SnowShock35** [comment]
Support should be there for 1.16.5 now so feel free to give it a try.
