### ISSUE TITLE
JEI Integration causes error during loading modpack.

### ISSUE THREAD

**Issue by toErIpNid** [SnowShock35/jei-integration#19]
Or at least I think it does. The modpack works when I disable the mod. 

Log: 
[crash-2021-09-06_20.17.36-fml.txt](https://github.com/SnowShock35/jei-integration/files/7118285/crash-2021-09-06_20.17.36-fml.txt)

**Comment by SnowShock35** [comment]
Looks more like a JEI issue rather than a JEI Integration issue. Try updating the mod and see if that fixes the issue. I've fixed a few issues in later versions.
