### ISSUE TITLE
Can I transfer this MOD to Chinese Website www.mcbbs.net?I'll link here.

### ISSUE THREAD

**Issue by 2173204318** [SnowShock35/jei-integration#2]
Hi,Can I transfer this MOD to Chinese Website www.mcbbs.net?I'll link here.
And This is Chinese Language

{
  "_comment": "JEI扩展 语言文件",

  "_comment": "语言名: 中文",
  "_comment": "使用此语言的区域: 中国(大陆)",
  "_comment": "国际语言代码: zh_cn",

  "_comment": "配置",
  "config.jeiintegration.tooltips.burnTimeTooltipMode": "燃烧时间显示",
  "config.jeiintegration.tooltips.durabilityTooltipMode": "耐久度显示",
  "config.jeiintegration.tooltips.foodTooltipMode": "食物能够恢复的饥饿值显示",
  "config.jeiintegration.tooltips.maxStackSizeTooltipMode": "物品最大堆叠数显示",
  "config.jeiintegration.tooltips.nbtTooltipMode": "物品NBT数据显示",
  "config.jeiintegration.tooltips.registryNameTooltipMode": "物品ID显示",
  "config.jeiintegration.tooltips.tagsTooltipMode": "物品标签显示",
  "config.jeiintegration.tooltips.translationKeyTooltipMode": "物品本地化名显示",

  "_comment": "显示内容",
  "tooltip.jeiintegration.burnTime": "燃烧时间:",
  "tooltip.jeiintegration.burnTime.suffix": "ticks",
  "tooltip.jeiintegration.durability": "耐久值:",
  "tooltip.jeiintegration.hunger": "饥饿值:",
  "tooltip.jeiintegration.saturation": "饱和度:",
  "tooltip.jeiintegration.maxStackSize": "最大堆叠数量:",
  "tooltip.jeiintegration.nbtTagData": "NBT:",
  "tooltip.jeiintegration.registryName": "ID:",
  "tooltip.jeiintegration.tags": "标签:",
  "tooltip.jeiintegration.translationKey": "物品本地化名:"
}

**Comment by SnowShock35** [comment]
You're not permitted to rehost this mod, period. If you create a pull request I will merge the translation file to the mod. 😃
