### ISSUE TITLE
Crash when starting minecraft

### ISSUE THREAD

**Issue by DoctorSigma** [SnowShock35/jei-integration#25]
When I first ran disassembled this modpack. I was shocked, in the report I saw line (2) where it was written about your mod. I removed your mod and minecraft started ...
[crash-2022-01-13_13.39.46-client.txt](https://github.com/SnowShock35/jei-integration/files/7870388/crash-2022-01-13_13.39.46-client.txt)

**Comment by SnowShock35** [comment]
Try again with the latest version.
