### ISSUE TITLE
is there gona be 1.19+?

### ISSUE THREAD

**Issue by hallool** [SnowShock35/jei-integration#38]
hello i am playing on 1.19.2 at the moment and cant find any mod but this one that displays durability in jei.. but this mod is 1.18.2 max..

**Comment by vizthex123** [comment]
Yeah, I'm really missing this mod in my new 1.19.2 pack. Love the ability to view tags and burn time.

**Comment by F0x06** [comment]
Hi, i ported the mod to `1.19.2` see https://github.com/SnowShock35/jei-integration/pull/39

**Comment by vizthex123** [comment]
> Hi, i ported the mod to `1.19.2` see #39

 i don't suppose you made a CurseForge page so i could add it to my public modpacks? Would be awesome if so.

**Comment by F0x06** [comment]
> > Hi, i ported the mod to `1.19.2` see #39
> 
> i don't suppose you made a CurseForge page so i could add it to my public modpacks? Would be awesome if so.

The best option is to wait for @SnowShock35 to merge the PR I guess :/. I hope soon

**Comment by SnowShock35** [comment]
1.19.2 will be available shortly. Please give your thanks to @F0x06 for their hard work and for donating their time to port the mod. 😄

**Comment by vizthex123** [comment]
> 1.19.2 will be available shortly. Please give your thanks to @F0x06 for their hard work and for donating their time to port the mod. 😄

pog, thanks @F0x06.

**Comment by F0x06** [comment]
Hi @SnowShock35, i still don't see `1.19.2` on Curseforge, can you upload it please :) ? 

Thanks.
