### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hrndz16** [SnowShock35/jei-integration#4]
I currently play on Minecraft version 1.16.3, and I installed the mod but it doesn't work. in the game it appears that it is correctly installed but it does not work in the game :(

**Comment by SnowShock35** [comment]
I need more information than this. Please provide the version of Forge and the version of the mod so I can better determine why it isn't working.

**Comment by MarkelL12** [comment]
Mine seems to not show up. 
Mod version: 6.0.0.8
Minecraft Version: 1.16.3
Forge Version: 34.0.7
Please let me know if there is anything else you need. I would love to see jei/nei in 1.1.6.3

**Comment by SnowShock35** [comment]
Did you enable the tooltips in the config file @MarkelL12

**Comment by SnowShock35** [comment]
Closing - no response.
