### ISSUE TITLE
Checking In on Project Activity and Offering Assistance

### ISSUE THREAD

**Issue by F0x06** [SnowShock35/jei-integration#41]
Hello @SnowShock35,

I hope this message finds you doing well. I've noticed there hasn't been much activity in the repository for more than a year now. I understand that maintaining an open-source project can be quite a commitment, and life’s other responsibilities often take priority.

I’ve previously submitted two pull requests (#39 and #40) that haven’t received feedback yet. I made these contributions in hopes of enhancing the project and remain eager to continue supporting its development.

With the recent quiet period, I just wanted to reach out and see if everything is okay and if there are any plans for the project moving forward. If time is a constraint for you right now, I'd be more than willing to lend a hand. Whether it's helping manage the repository, reviewing pull requests, or discussing the possibility of a fork if that's more suitable under the current circumstances, I’m here to help.

I’m looking forward to hearing your thoughts and am open to discussing any ways in which I can be of assistance to ensure the project's ongoing success.

Thanks for all the effort you’ve put into this project. I’m excited about the possibility of contributing further.

Best regards,
F0x

**Comment by F0x06** [comment]
Hi @SnowShock35, thanks for merging all my PRs :) , I will try to help in the future when I have time, have a nice day.

**Comment by SnowShock35** [comment]
No, thank you @F0x06 for updating the mod. I'll try get it up on CF and Modrinth ASAP.
