### ISSUE TITLE
Long NBT dont wrap text...

### ISSUE THREAD

**Issue by zanecek** [SnowShock35/jei-integration#6]
...and tooltip windows is therefore broken:

![2020-09-25_23 20 02](https://user-images.githubusercontent.com/62807156/94327859-25b17280-ffae-11ea-85b8-6ba35c799eb2.png)

And, secondly, TAGs, even if it is allowed, dont show without NBT is enabled too.

**Comment by SnowShock35** [comment]
So wrapping unfortunately is just a limitation of the tooltip implementation in Minecraft and I don't feel like writing a custom one for small edge-cases like this. The NBT tooltip isn't overly useful in most cases nowadays with such a large reliance on tags as opposed to NBT. 

My advice is to change the GUI scale or use another tool to see NBT. 

As for the other issue you mentioned I believe that's now fixed. Thanks for letting me know though 👍🏻
