### ISSUE TITLE
config file / tooltip settings get reset to disabled

### ISSUE THREAD

**Issue by instinxx** [SnowShock35/jei-integration#7]
Upon worldload all tooltip settings change from enabled to disabled.

Also what is the proper syntax for Handler and Misc settings?

My config : https://pastebin.com/qtw3wSRw

**Comment by SnowShock35** [comment]
Your config looks correct so I don't know why it's not working. I recommend deleting that generated file and then changing settings from within the in-game config.

1. Load up game with Forge, JEI and JEI Integration installed
2. Click the `Mods` button on the main menu
3. Find and select JEI Integration
4. Click the `Config` button 
5. Click the `Tooltip Settings` button
6. Change the options you want by clicking the relevant  buttons

As for Handler and Misc settings, there's nothing currently available for this hence why they're empty.
